name: Complex

on: push

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
    - run: date
  windows-job:
    runs-on: windows-latest
    steps:
    - run: date
  mac-job:
    runs-on: macos-latest
    steps:
    - run: date
  depends-job:
    needs: [ubuntu-job, windows-job, mac-job]
    runs-on: macos-latest
    steps:
    - run: date
